### PR TITLE
Phaniarnab hometown

### LINKED ISSUE #60: Create a new file for phaniarnab hometown
## Add file for Fuquay NC
- [ ] Create a branch
- [ ] Add my file
- [ ] Create a commit
- [ ] Open a pull request
- [ ] Have a discussion about the pull request
- [ ] Merge our pull request

### PR DESCRIPTION
**Pull request by phaniarnab**
closes #60

### CODE REVIEW

**Comment by argyleskull** [comment]
Here is a comment!

**Comment by i71186** [comment]
what's your hometown?

**Comment by i71186** [comment]
Sorry, I realize now...Kolkatta thats great

**Comment by wayuyao** [comment]
@phaniarnab looks good

**Comment by i71186** [comment]
looks good :shipit:

**Pull request merged**
